[project]
name = "talktoyourdata-two"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.4",
    "fastapi[standard]>=0.135.3",
    "pydantic-ai>=1.80.0",
    "pydantic-settings>=2.13.1",
    "sqlmodel>=0.0.38",
]
