[project]
name = "talktoyourdata-two"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.4",
    "aiosqlite>=0.21.0",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.135.3",
    "psycopg[binary]>=3.2.12",
    "pydantic-ai>=1.80.0",
    "pydantic-settings>=2.13.1",
    "pytest>=8.4.2",
    "sqlmodel>=0.0.38",
]
